config/routes.rb
Destroyer::Application.routes.draw do

  match "pages/*id" => "pages#show", format: false

  resources :pages, only: [:new, :create, :show]

  root to: 'pages#new'
  devise_for :users

  # match "*path" => redirect { |params| "pageso/#{params[:path]}" }
  
end

app/models/page.rb
require 'nokogiri'
require 'open-uri'
require 'open_uri_redirections'
require 'dreadnought'

class Page < ActiveRecord::Base
  extend FriendlyId
  friendly_id :url, use: :slugged
 
  validates :url, presence: true, url: true
  attr_accessible :content, :url

  def normalize_friendly_id(string)
    string
  end

  def populate_content
    content = open('http://' + url, allow_redirections: :all).read
    content = PathProcessor.new(url, content).process_paths
    self.update_attributes(content: content)
  end

  def destroyed_content
    populate_content if content.nil?
    Dreadnought.new(content).destroy
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  respond_to :html
  
  def self.exposes(*methods)
    attr_reader *methods
    helper_method *methods
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def new
    respond_with @page = Page.new
  end

  def create
    existing_pages = Page.where(url: params[:page]['url'])
    existing_pages.sort_by! { |p| p['slug'] }
    @existing_page = existing_pages.first
    
    unless @existing_page.nil?
      respond_with @existing_page and return
    end

    @page = Page.create(params[:page])
    if @page.save
      respond_with @page
    else
      render action: 'new'
    end
  end

  def show
    begin
      respond_with @page = Page.find(params['id']), layout: false
    rescue ActiveRecord::RecordNotFound
      @page = Page.create(url: params['id'])
      if @page.save
        respond_with @page
      else
        render action: 'new'
      end
    end
  end

end

app/views/home/index.html.slim
/ Nothing to see here

app/views/layouts/application.html.slim
doctype html
html
  head
    title Destroyer

    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tag

  body
    - if notice
      p.flash.flash-notice= notice

    - if alert
      p.flash.flash-alert= alert

    == yield

app/views/pages/_form.html.slim
= form_for @page do |f|
  - if @page.errors.any?
    #error_explanation
      h2 = "#{pluralize(@page.errors.count, "error")} prohibited this page from being saved:"
      ul
        - @page.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :url
    = f.text_field :url
  .actions = f.submit 'Save'

app/views/pages/edit.html.slim
h1 Editing page

== render 'form'

= link_to 'Show', @page
'|
= link_to 'Back', pages_path

app/views/pages/index.html.slim
h1 Listing pages

table
  tr
    th Url
    th Content
    th
    th
    th

  - @pages.each do |page|
    tr
      td = page.url
      td = page.content
      td = link_to 'Show', page
      td = link_to 'Edit', edit_page_path(page)
      td = link_to 'Destroy', page, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Page', new_page_path

app/views/pages/new.html.slim
h1 New page

== render 'form'

= link_to 'Back', pages_path

app/views/pages/show.html.slim
== @page.destroyed_content